// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: flow_chart.proto

package rpc_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_flow_chart_proto protoreflect.FileDescriptor

var file_flow_chart_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x1a, 0x11, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xa9, 0x01,
	0x0a, 0x09, 0x46, 0x6c, 0x6f, 0x77, 0x43, 0x68, 0x61, 0x72, 0x74, 0x12, 0x2d, 0x0a, 0x04, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50,
	0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x03, 0x41, 0x64,
	0x64, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c,
	0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x25,
	0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70,
	0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x0b, 0x2e, 0x72,
	0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x5f,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var file_flow_chart_proto_goTypes = []interface{}{
	(*PagerReq)(nil),  // 0: rpc_pb.PagerReq
	(*Req)(nil),       // 1: rpc_pb.Req
	(*PagerResp)(nil), // 2: rpc_pb.PagerResp
	(*Resp)(nil),      // 3: rpc_pb.Resp
}
var file_flow_chart_proto_depIdxs = []int32{
	0, // 0: rpc_pb.FlowChart.List:input_type -> rpc_pb.PagerReq
	1, // 1: rpc_pb.FlowChart.Add:input_type -> rpc_pb.Req
	1, // 2: rpc_pb.FlowChart.Update:input_type -> rpc_pb.Req
	1, // 3: rpc_pb.FlowChart.Del:input_type -> rpc_pb.Req
	2, // 4: rpc_pb.FlowChart.List:output_type -> rpc_pb.PagerResp
	3, // 5: rpc_pb.FlowChart.Add:output_type -> rpc_pb.Resp
	3, // 6: rpc_pb.FlowChart.Update:output_type -> rpc_pb.Resp
	3, // 7: rpc_pb.FlowChart.Del:output_type -> rpc_pb.Resp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flow_chart_proto_init() }
func file_flow_chart_proto_init() {
	if File_flow_chart_proto != nil {
		return
	}
	file_user_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_flow_chart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_flow_chart_proto_goTypes,
		DependencyIndexes: file_flow_chart_proto_depIdxs,
	}.Build()
	File_flow_chart_proto = out.File
	file_flow_chart_proto_rawDesc = nil
	file_flow_chart_proto_goTypes = nil
	file_flow_chart_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FlowChartClient is the client API for FlowChart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlowChartClient interface {
	List(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error)
	Add(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	Update(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	Del(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type flowChartClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowChartClient(cc grpc.ClientConnInterface) FlowChartClient {
	return &flowChartClient{cc}
}

func (c *flowChartClient) List(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error) {
	out := new(PagerResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.FlowChart/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowChartClient) Add(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.FlowChart/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowChartClient) Update(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.FlowChart/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *flowChartClient) Del(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.FlowChart/Del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlowChartServer is the server API for FlowChart service.
type FlowChartServer interface {
	List(context.Context, *PagerReq) (*PagerResp, error)
	Add(context.Context, *Req) (*Resp, error)
	Update(context.Context, *Req) (*Resp, error)
	Del(context.Context, *Req) (*Resp, error)
}

// UnimplementedFlowChartServer can be embedded to have forward compatible implementations.
type UnimplementedFlowChartServer struct {
}

func (*UnimplementedFlowChartServer) List(context.Context, *PagerReq) (*PagerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedFlowChartServer) Add(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedFlowChartServer) Update(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedFlowChartServer) Del(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}

func RegisterFlowChartServer(s *grpc.Server, srv FlowChartServer) {
	s.RegisterService(&_FlowChart_serviceDesc, srv)
}

func _FlowChart_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowChartServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.FlowChart/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowChartServer).List(ctx, req.(*PagerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowChart_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowChartServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.FlowChart/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowChartServer).Add(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowChart_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowChartServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.FlowChart/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowChartServer).Update(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _FlowChart_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlowChartServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.FlowChart/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlowChartServer).Del(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlowChart_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_pb.FlowChart",
	HandlerType: (*FlowChartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _FlowChart_List_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _FlowChart_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _FlowChart_Update_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _FlowChart_Del_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "flow_chart.proto",
}
