// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: menu.proto

package rpc_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_menu_proto protoreflect.FileDescriptor

var file_menu_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x70,
	0x63, 0x5f, 0x70, 0x62, 0x1a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x83, 0x05, 0x0a, 0x04, 0x4d, 0x65, 0x6e, 0x75,
	0x12, 0x2d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70,
	0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x72, 0x70, 0x63,
	0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x22, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63,
	0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c,
	0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x33,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x10, 0x2e, 0x72,
	0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4d, 0x65,
	0x6e, 0x75, 0x12, 0x10, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65,
	0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61,
	0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x2e, 0x72, 0x70, 0x63,
	0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x72,
	0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x30, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x10, 0x2e, 0x72,
	0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x0b,
	0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70,
	0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x07, 0x44,
	0x65, 0x6c, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x08, 0x45, 0x64, 0x69, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x12,
	0x0b, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72,
	0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0d,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x6f, 0x70, 0x4d, 0x65, 0x6e, 0x75, 0x12, 0x0b, 0x2e,
	0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63,
	0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x6e, 0x75, 0x57, 0x69, 0x74, 0x68, 0x41, 0x75, 0x74, 0x68, 0x12, 0x10, 0x2e,
	0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a,
	0x11, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x12, 0x27, 0x0a, 0x08, 0x53, 0x6f, 0x72, 0x74, 0x4d, 0x65, 0x6e, 0x75,
	0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e,
	0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_menu_proto_goTypes = []interface{}{
	(*PagerReq)(nil),  // 0: rpc_pb.PagerReq
	(*Req)(nil),       // 1: rpc_pb.Req
	(*PagerResp)(nil), // 2: rpc_pb.PagerResp
	(*Resp)(nil),      // 3: rpc_pb.Resp
}
var file_menu_proto_depIdxs = []int32{
	0,  // 0: rpc_pb.Menu.List:input_type -> rpc_pb.PagerReq
	1,  // 1: rpc_pb.Menu.Add:input_type -> rpc_pb.Req
	1,  // 2: rpc_pb.Menu.Del:input_type -> rpc_pb.Req
	1,  // 3: rpc_pb.Menu.Update:input_type -> rpc_pb.Req
	0,  // 4: rpc_pb.Menu.GetAllMenu:input_type -> rpc_pb.PagerReq
	0,  // 5: rpc_pb.Menu.GetUserMenu:input_type -> rpc_pb.PagerReq
	0,  // 6: rpc_pb.Menu.GetUserAction:input_type -> rpc_pb.PagerReq
	0,  // 7: rpc_pb.Menu.GetMenu:input_type -> rpc_pb.PagerReq
	1,  // 8: rpc_pb.Menu.AddMenu:input_type -> rpc_pb.Req
	1,  // 9: rpc_pb.Menu.DelMenu:input_type -> rpc_pb.Req
	1,  // 10: rpc_pb.Menu.EditMenu:input_type -> rpc_pb.Req
	1,  // 11: rpc_pb.Menu.StartStopMenu:input_type -> rpc_pb.Req
	0,  // 12: rpc_pb.Menu.GetMenuWithAuth:input_type -> rpc_pb.PagerReq
	1,  // 13: rpc_pb.Menu.SortMenu:input_type -> rpc_pb.Req
	2,  // 14: rpc_pb.Menu.List:output_type -> rpc_pb.PagerResp
	3,  // 15: rpc_pb.Menu.Add:output_type -> rpc_pb.Resp
	3,  // 16: rpc_pb.Menu.Del:output_type -> rpc_pb.Resp
	3,  // 17: rpc_pb.Menu.Update:output_type -> rpc_pb.Resp
	2,  // 18: rpc_pb.Menu.GetAllMenu:output_type -> rpc_pb.PagerResp
	2,  // 19: rpc_pb.Menu.GetUserMenu:output_type -> rpc_pb.PagerResp
	2,  // 20: rpc_pb.Menu.GetUserAction:output_type -> rpc_pb.PagerResp
	2,  // 21: rpc_pb.Menu.GetMenu:output_type -> rpc_pb.PagerResp
	3,  // 22: rpc_pb.Menu.AddMenu:output_type -> rpc_pb.Resp
	3,  // 23: rpc_pb.Menu.DelMenu:output_type -> rpc_pb.Resp
	3,  // 24: rpc_pb.Menu.EditMenu:output_type -> rpc_pb.Resp
	3,  // 25: rpc_pb.Menu.StartStopMenu:output_type -> rpc_pb.Resp
	2,  // 26: rpc_pb.Menu.GetMenuWithAuth:output_type -> rpc_pb.PagerResp
	3,  // 27: rpc_pb.Menu.SortMenu:output_type -> rpc_pb.Resp
	14, // [14:28] is the sub-list for method output_type
	0,  // [0:14] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_menu_proto_init() }
func file_menu_proto_init() {
	if File_menu_proto != nil {
		return
	}
	file_user_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_menu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menu_proto_goTypes,
		DependencyIndexes: file_menu_proto_depIdxs,
	}.Build()
	File_menu_proto = out.File
	file_menu_proto_rawDesc = nil
	file_menu_proto_goTypes = nil
	file_menu_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MenuClient is the client API for Menu service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MenuClient interface {
	List(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error)
	Add(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	Del(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	Update(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	GetAllMenu(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error)
	GetUserMenu(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error)
	GetUserAction(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error)
	GetMenu(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error)
	AddMenu(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	DelMenu(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	EditMenu(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	StartStopMenu(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	GetMenuWithAuth(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error)
	SortMenu(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type menuClient struct {
	cc grpc.ClientConnInterface
}

func NewMenuClient(cc grpc.ClientConnInterface) MenuClient {
	return &menuClient{cc}
}

func (c *menuClient) List(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error) {
	out := new(PagerResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) Add(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) Del(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/Del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) Update(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) GetAllMenu(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error) {
	out := new(PagerResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/GetAllMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) GetUserMenu(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error) {
	out := new(PagerResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/GetUserMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) GetUserAction(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error) {
	out := new(PagerResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/GetUserAction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) GetMenu(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error) {
	out := new(PagerResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/GetMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) AddMenu(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/AddMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) DelMenu(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/DelMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) EditMenu(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/EditMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) StartStopMenu(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/StartStopMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) GetMenuWithAuth(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error) {
	out := new(PagerResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/GetMenuWithAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuClient) SortMenu(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Menu/SortMenu", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MenuServer is the server API for Menu service.
type MenuServer interface {
	List(context.Context, *PagerReq) (*PagerResp, error)
	Add(context.Context, *Req) (*Resp, error)
	Del(context.Context, *Req) (*Resp, error)
	Update(context.Context, *Req) (*Resp, error)
	GetAllMenu(context.Context, *PagerReq) (*PagerResp, error)
	GetUserMenu(context.Context, *PagerReq) (*PagerResp, error)
	GetUserAction(context.Context, *PagerReq) (*PagerResp, error)
	GetMenu(context.Context, *PagerReq) (*PagerResp, error)
	AddMenu(context.Context, *Req) (*Resp, error)
	DelMenu(context.Context, *Req) (*Resp, error)
	EditMenu(context.Context, *Req) (*Resp, error)
	StartStopMenu(context.Context, *Req) (*Resp, error)
	GetMenuWithAuth(context.Context, *PagerReq) (*PagerResp, error)
	SortMenu(context.Context, *Req) (*Resp, error)
}

// UnimplementedMenuServer can be embedded to have forward compatible implementations.
type UnimplementedMenuServer struct {
}

func (*UnimplementedMenuServer) List(context.Context, *PagerReq) (*PagerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedMenuServer) Add(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedMenuServer) Del(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (*UnimplementedMenuServer) Update(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedMenuServer) GetAllMenu(context.Context, *PagerReq) (*PagerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllMenu not implemented")
}
func (*UnimplementedMenuServer) GetUserMenu(context.Context, *PagerReq) (*PagerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserMenu not implemented")
}
func (*UnimplementedMenuServer) GetUserAction(context.Context, *PagerReq) (*PagerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserAction not implemented")
}
func (*UnimplementedMenuServer) GetMenu(context.Context, *PagerReq) (*PagerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMenu not implemented")
}
func (*UnimplementedMenuServer) AddMenu(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMenu not implemented")
}
func (*UnimplementedMenuServer) DelMenu(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelMenu not implemented")
}
func (*UnimplementedMenuServer) EditMenu(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditMenu not implemented")
}
func (*UnimplementedMenuServer) StartStopMenu(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartStopMenu not implemented")
}
func (*UnimplementedMenuServer) GetMenuWithAuth(context.Context, *PagerReq) (*PagerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMenuWithAuth not implemented")
}
func (*UnimplementedMenuServer) SortMenu(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SortMenu not implemented")
}

func RegisterMenuServer(s *grpc.Server, srv MenuServer) {
	s.RegisterService(&_Menu_serviceDesc, srv)
}

func _Menu_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).List(ctx, req.(*PagerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).Add(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).Del(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).Update(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_GetAllMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).GetAllMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/GetAllMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).GetAllMenu(ctx, req.(*PagerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_GetUserMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).GetUserMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/GetUserMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).GetUserMenu(ctx, req.(*PagerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_GetUserAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).GetUserAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/GetUserAction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).GetUserAction(ctx, req.(*PagerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_GetMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).GetMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/GetMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).GetMenu(ctx, req.(*PagerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_AddMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).AddMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/AddMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).AddMenu(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_DelMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).DelMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/DelMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).DelMenu(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_EditMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).EditMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/EditMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).EditMenu(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_StartStopMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).StartStopMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/StartStopMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).StartStopMenu(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_GetMenuWithAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).GetMenuWithAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/GetMenuWithAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).GetMenuWithAuth(ctx, req.(*PagerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Menu_SortMenu_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuServer).SortMenu(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Menu/SortMenu",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuServer).SortMenu(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Menu_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_pb.Menu",
	HandlerType: (*MenuServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Menu_List_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Menu_Add_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Menu_Del_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Menu_Update_Handler,
		},
		{
			MethodName: "GetAllMenu",
			Handler:    _Menu_GetAllMenu_Handler,
		},
		{
			MethodName: "GetUserMenu",
			Handler:    _Menu_GetUserMenu_Handler,
		},
		{
			MethodName: "GetUserAction",
			Handler:    _Menu_GetUserAction_Handler,
		},
		{
			MethodName: "GetMenu",
			Handler:    _Menu_GetMenu_Handler,
		},
		{
			MethodName: "AddMenu",
			Handler:    _Menu_AddMenu_Handler,
		},
		{
			MethodName: "DelMenu",
			Handler:    _Menu_DelMenu_Handler,
		},
		{
			MethodName: "EditMenu",
			Handler:    _Menu_EditMenu_Handler,
		},
		{
			MethodName: "StartStopMenu",
			Handler:    _Menu_StartStopMenu_Handler,
		},
		{
			MethodName: "GetMenuWithAuth",
			Handler:    _Menu_GetMenuWithAuth_Handler,
		},
		{
			MethodName: "SortMenu",
			Handler:    _Menu_SortMenu_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "menu.proto",
}
