// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: org.proto

package rpc_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrgReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OrgReq) Reset() {
	*x = OrgReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgReq) ProtoMessage() {}

func (x *OrgReq) ProtoReflect() protoreflect.Message {
	mi := &file_org_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgReq.ProtoReflect.Descriptor instead.
func (*OrgReq) Descriptor() ([]byte, []int) {
	return file_org_proto_rawDescGZIP(), []int{0}
}

func (x *OrgReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OrgResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *OrgResp) Reset() {
	*x = OrgResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_org_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgResp) ProtoMessage() {}

func (x *OrgResp) ProtoReflect() protoreflect.Message {
	mi := &file_org_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgResp.ProtoReflect.Descriptor instead.
func (*OrgResp) Descriptor() ([]byte, []int) {
	return file_org_proto_rawDescGZIP(), []int{1}
}

func (x *OrgResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_org_proto protoreflect.FileDescriptor

var file_org_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x70, 0x63,
	0x5f, 0x70, 0x62, 0x1a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x06, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x23, 0x0a, 0x07, 0x4f, 0x72,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0xec, 0x02, 0x0a, 0x03, 0x4f, 0x72, 0x67, 0x12, 0x2d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x10, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x1a, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x28, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x0e, 0x2e,
	0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e,
	0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00,
	0x12, 0x28, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62,
	0x2e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62,
	0x2e, 0x4f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x06, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x4f, 0x72,
	0x67, 0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x4f, 0x72,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x50,
	0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62,
	0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2c, 0x0a, 0x0d,
	0x45, 0x64, 0x69, 0x74, 0x4f, 0x72, 0x67, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x2e,
	0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63,
	0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2a, 0x0a, 0x0b, 0x42, 0x61,
	0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x4f, 0x72, 0x67, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x5f,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x26, 0x0a, 0x07, 0x53, 0x6f, 0x72, 0x74, 0x4f, 0x72,
	0x67, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c,
	0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_org_proto_rawDescOnce sync.Once
	file_org_proto_rawDescData = file_org_proto_rawDesc
)

func file_org_proto_rawDescGZIP() []byte {
	file_org_proto_rawDescOnce.Do(func() {
		file_org_proto_rawDescData = protoimpl.X.CompressGZIP(file_org_proto_rawDescData)
	})
	return file_org_proto_rawDescData
}

var file_org_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_org_proto_goTypes = []interface{}{
	(*OrgReq)(nil),    // 0: rpc_pb.OrgReq
	(*OrgResp)(nil),   // 1: rpc_pb.OrgResp
	(*PagerReq)(nil),  // 2: rpc_pb.PagerReq
	(*Req)(nil),       // 3: rpc_pb.Req
	(*PagerResp)(nil), // 4: rpc_pb.PagerResp
	(*Resp)(nil),      // 5: rpc_pb.Resp
}
var file_org_proto_depIdxs = []int32{
	2, // 0: rpc_pb.Org.List:input_type -> rpc_pb.PagerReq
	0, // 1: rpc_pb.Org.Add:input_type -> rpc_pb.OrgReq
	0, // 2: rpc_pb.Org.Del:input_type -> rpc_pb.OrgReq
	0, // 3: rpc_pb.Org.Update:input_type -> rpc_pb.OrgReq
	2, // 4: rpc_pb.Org.GetOrgList:input_type -> rpc_pb.PagerReq
	3, // 5: rpc_pb.Org.EditOrgStatus:input_type -> rpc_pb.Req
	3, // 6: rpc_pb.Org.BatchDelOrg:input_type -> rpc_pb.Req
	3, // 7: rpc_pb.Org.SortOrg:input_type -> rpc_pb.Req
	4, // 8: rpc_pb.Org.List:output_type -> rpc_pb.PagerResp
	1, // 9: rpc_pb.Org.Add:output_type -> rpc_pb.OrgResp
	1, // 10: rpc_pb.Org.Del:output_type -> rpc_pb.OrgResp
	1, // 11: rpc_pb.Org.Update:output_type -> rpc_pb.OrgResp
	4, // 12: rpc_pb.Org.GetOrgList:output_type -> rpc_pb.PagerResp
	5, // 13: rpc_pb.Org.EditOrgStatus:output_type -> rpc_pb.Resp
	5, // 14: rpc_pb.Org.BatchDelOrg:output_type -> rpc_pb.Resp
	5, // 15: rpc_pb.Org.SortOrg:output_type -> rpc_pb.Resp
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_org_proto_init() }
func file_org_proto_init() {
	if File_org_proto != nil {
		return
	}
	file_user_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_org_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_org_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrgResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_org_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_org_proto_goTypes,
		DependencyIndexes: file_org_proto_depIdxs,
		MessageInfos:      file_org_proto_msgTypes,
	}.Build()
	File_org_proto = out.File
	file_org_proto_rawDesc = nil
	file_org_proto_goTypes = nil
	file_org_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrgClient is the client API for Org service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrgClient interface {
	List(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error)
	Add(ctx context.Context, in *OrgReq, opts ...grpc.CallOption) (*OrgResp, error)
	Del(ctx context.Context, in *OrgReq, opts ...grpc.CallOption) (*OrgResp, error)
	Update(ctx context.Context, in *OrgReq, opts ...grpc.CallOption) (*OrgResp, error)
	GetOrgList(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error)
	EditOrgStatus(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	BatchDelOrg(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	SortOrg(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type orgClient struct {
	cc grpc.ClientConnInterface
}

func NewOrgClient(cc grpc.ClientConnInterface) OrgClient {
	return &orgClient{cc}
}

func (c *orgClient) List(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error) {
	out := new(PagerResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Org/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) Add(ctx context.Context, in *OrgReq, opts ...grpc.CallOption) (*OrgResp, error) {
	out := new(OrgResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Org/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) Del(ctx context.Context, in *OrgReq, opts ...grpc.CallOption) (*OrgResp, error) {
	out := new(OrgResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Org/Del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) Update(ctx context.Context, in *OrgReq, opts ...grpc.CallOption) (*OrgResp, error) {
	out := new(OrgResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Org/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) GetOrgList(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error) {
	out := new(PagerResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Org/GetOrgList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) EditOrgStatus(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Org/EditOrgStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) BatchDelOrg(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Org/BatchDelOrg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orgClient) SortOrg(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Org/SortOrg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrgServer is the server API for Org service.
type OrgServer interface {
	List(context.Context, *PagerReq) (*PagerResp, error)
	Add(context.Context, *OrgReq) (*OrgResp, error)
	Del(context.Context, *OrgReq) (*OrgResp, error)
	Update(context.Context, *OrgReq) (*OrgResp, error)
	GetOrgList(context.Context, *PagerReq) (*PagerResp, error)
	EditOrgStatus(context.Context, *Req) (*Resp, error)
	BatchDelOrg(context.Context, *Req) (*Resp, error)
	SortOrg(context.Context, *Req) (*Resp, error)
}

// UnimplementedOrgServer can be embedded to have forward compatible implementations.
type UnimplementedOrgServer struct {
}

func (*UnimplementedOrgServer) List(context.Context, *PagerReq) (*PagerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedOrgServer) Add(context.Context, *OrgReq) (*OrgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedOrgServer) Del(context.Context, *OrgReq) (*OrgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (*UnimplementedOrgServer) Update(context.Context, *OrgReq) (*OrgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedOrgServer) GetOrgList(context.Context, *PagerReq) (*PagerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrgList not implemented")
}
func (*UnimplementedOrgServer) EditOrgStatus(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditOrgStatus not implemented")
}
func (*UnimplementedOrgServer) BatchDelOrg(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDelOrg not implemented")
}
func (*UnimplementedOrgServer) SortOrg(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SortOrg not implemented")
}

func RegisterOrgServer(s *grpc.Server, srv OrgServer) {
	s.RegisterService(&_Org_serviceDesc, srv)
}

func _Org_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Org/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).List(ctx, req.(*PagerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Org/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).Add(ctx, req.(*OrgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Org/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).Del(ctx, req.(*OrgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Org/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).Update(ctx, req.(*OrgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_GetOrgList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).GetOrgList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Org/GetOrgList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).GetOrgList(ctx, req.(*PagerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_EditOrgStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).EditOrgStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Org/EditOrgStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).EditOrgStatus(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_BatchDelOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).BatchDelOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Org/BatchDelOrg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).BatchDelOrg(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Org_SortOrg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgServer).SortOrg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Org/SortOrg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgServer).SortOrg(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Org_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_pb.Org",
	HandlerType: (*OrgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Org_List_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Org_Add_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Org_Del_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Org_Update_Handler,
		},
		{
			MethodName: "GetOrgList",
			Handler:    _Org_GetOrgList_Handler,
		},
		{
			MethodName: "EditOrgStatus",
			Handler:    _Org_EditOrgStatus_Handler,
		},
		{
			MethodName: "BatchDelOrg",
			Handler:    _Org_BatchDelOrg_Handler,
		},
		{
			MethodName: "SortOrg",
			Handler:    _Org_SortOrg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "org.proto",
}
