// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: rule.proto

package rpc_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_rule_proto protoreflect.FileDescriptor

var file_rule_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x72, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x70,
	0x63, 0x5f, 0x70, 0x62, 0x1a, 0x11, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0xfc, 0x01, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65,
	0x12, 0x2d, 0x0a, 0x04, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x10, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70,
	0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x72, 0x70, 0x63,
	0x5f, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x22, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63,
	0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c,
	0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x27,
	0x0a, 0x08, 0x42, 0x61, 0x74, 0x63, 0x68, 0x44, 0x65, 0x6c, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63,
	0x5f, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x0e, 0x45, 0x64, 0x69, 0x74, 0x52,
	0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x2e, 0x72, 0x70, 0x63, 0x5f,
	0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_rule_proto_goTypes = []interface{}{
	(*PagerReq)(nil),  // 0: rpc_pb.PagerReq
	(*Req)(nil),       // 1: rpc_pb.Req
	(*PagerResp)(nil), // 2: rpc_pb.PagerResp
	(*Resp)(nil),      // 3: rpc_pb.Resp
}
var file_rule_proto_depIdxs = []int32{
	0, // 0: rpc_pb.Rule.List:input_type -> rpc_pb.PagerReq
	1, // 1: rpc_pb.Rule.Add:input_type -> rpc_pb.Req
	1, // 2: rpc_pb.Rule.Del:input_type -> rpc_pb.Req
	1, // 3: rpc_pb.Rule.Update:input_type -> rpc_pb.Req
	1, // 4: rpc_pb.Rule.BatchDel:input_type -> rpc_pb.Req
	1, // 5: rpc_pb.Rule.EditRuleStatus:input_type -> rpc_pb.Req
	2, // 6: rpc_pb.Rule.List:output_type -> rpc_pb.PagerResp
	3, // 7: rpc_pb.Rule.Add:output_type -> rpc_pb.Resp
	3, // 8: rpc_pb.Rule.Del:output_type -> rpc_pb.Resp
	3, // 9: rpc_pb.Rule.Update:output_type -> rpc_pb.Resp
	3, // 10: rpc_pb.Rule.BatchDel:output_type -> rpc_pb.Resp
	3, // 11: rpc_pb.Rule.EditRuleStatus:output_type -> rpc_pb.Resp
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rule_proto_init() }
func file_rule_proto_init() {
	if File_rule_proto != nil {
		return
	}
	file_user_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rule_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rule_proto_goTypes,
		DependencyIndexes: file_rule_proto_depIdxs,
	}.Build()
	File_rule_proto = out.File
	file_rule_proto_rawDesc = nil
	file_rule_proto_goTypes = nil
	file_rule_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RuleClient is the client API for Rule service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RuleClient interface {
	List(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error)
	Add(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	Del(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	Update(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	BatchDel(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	EditRuleStatus(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type ruleClient struct {
	cc grpc.ClientConnInterface
}

func NewRuleClient(cc grpc.ClientConnInterface) RuleClient {
	return &ruleClient{cc}
}

func (c *ruleClient) List(ctx context.Context, in *PagerReq, opts ...grpc.CallOption) (*PagerResp, error) {
	out := new(PagerResp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Rule/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleClient) Add(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Rule/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleClient) Del(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Rule/Del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleClient) Update(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Rule/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleClient) BatchDel(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Rule/BatchDel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ruleClient) EditRuleStatus(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/rpc_pb.Rule/EditRuleStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuleServer is the server API for Rule service.
type RuleServer interface {
	List(context.Context, *PagerReq) (*PagerResp, error)
	Add(context.Context, *Req) (*Resp, error)
	Del(context.Context, *Req) (*Resp, error)
	Update(context.Context, *Req) (*Resp, error)
	BatchDel(context.Context, *Req) (*Resp, error)
	EditRuleStatus(context.Context, *Req) (*Resp, error)
}

// UnimplementedRuleServer can be embedded to have forward compatible implementations.
type UnimplementedRuleServer struct {
}

func (*UnimplementedRuleServer) List(context.Context, *PagerReq) (*PagerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedRuleServer) Add(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedRuleServer) Del(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (*UnimplementedRuleServer) Update(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedRuleServer) BatchDel(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDel not implemented")
}
func (*UnimplementedRuleServer) EditRuleStatus(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditRuleStatus not implemented")
}

func RegisterRuleServer(s *grpc.Server, srv RuleServer) {
	s.RegisterService(&_Rule_serviceDesc, srv)
}

func _Rule_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Rule/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServer).List(ctx, req.(*PagerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rule_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Rule/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServer).Add(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rule_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Rule/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServer).Del(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rule_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Rule/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServer).Update(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rule_BatchDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServer).BatchDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Rule/BatchDel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServer).BatchDel(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rule_EditRuleStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuleServer).EditRuleStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc_pb.Rule/EditRuleStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuleServer).EditRuleStatus(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rule_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc_pb.Rule",
	HandlerType: (*RuleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Rule_List_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _Rule_Add_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _Rule_Del_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Rule_Update_Handler,
		},
		{
			MethodName: "BatchDel",
			Handler:    _Rule_BatchDel_Handler,
		},
		{
			MethodName: "EditRuleStatus",
			Handler:    _Rule_EditRuleStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rule.proto",
}
